In [2]:
import numpy as np
import pandas as pd

In [3]:
import seaborn as sns
import matplotlib as plt

In [4]:
sns.set_style('darkgrid')
plt.rcParams['figure.figsize']= (8,5)

In [5]:
df = pd.read_csv('6 class csv.csv')

In [6]:
df.head()

,Temperature (K),Luminosity(L/Lo),Radius(R/Ro),Absolute magnitude(Mv),Star type,Star color,Spectral Class
0,3068,0.002400,0.1700,16.12,0,Red,M
1,3042,0.000500,0.1542,16.60,0,Red,M
2,2600,0.000300,0.1020,18.70,0,Red,M
3,2800,0.000200,0.1600,16.65,0,Red,M
4,1939,0.000138,0.1030,20.06,0,Red,M

In [8]:
df.columns

Index(['Temperature (K)', 'Luminosity(L/Lo)', 'Radius(R/Ro)',
       'Absolute magnitude(Mv)', 'Star type', 'Star color', 'Spectral Class'],
      dtype='str')

In [10]:
df['Star color'].nunique()

19

In [11]:
df['Star color'].value_counts()

Star color
Red                   112
Blue                   55
Blue-white             26
Blue White             10
yellow-white            8
White                   7
Yellowish White         3
Blue white              3
white                   3
Whitish                 2
Orange                  2
yellowish               2
Pale yellow orange      1
White-Yellow            1
Blue                    1
Yellowish               1
Orange-Red              1
Blue white              1
Blue-White              1
Name: count, dtype: int64

In [12]:
df['Star color'] = df['Star color'].str.strip().str.lower()

In [ ]:
# *Removing anything that has hyphen in it.*

In [13]:
df['Star color'] = df['Star color'].str.replace('-',' ',regex = False)

In [17]:
# Collapse any repeated internal spaces left over 
# from the previous step.

In [14]:
df['Star color']=df['Star color'].str.split().str.join(' ')

In [18]:
# Make the some changes like white, yellow and white*yellow combo
# to Reduce any confusion

In [35]:
df['Star color'] = df['Star color'].replace({'yellowish white':'yellow white','white yellow':'yellow white'})

In [36]:
df['Star color'].nunique()

11

In [24]:
df

,Temperature (K),Luminosity(L/Lo),Radius(R/Ro),Absolute magnitude(Mv),Star type,Star color,Spectral Class
0,3068,0.002400,0.1700,16.12,0,red,M
1,3042,0.000500,0.1542,16.60,0,red,M
2,2600,0.000300,0.1020,18.70,0,red,M
3,2800,0.000200,0.1600,16.65,0,red,M
4,1939,0.000138,0.1030,20.06,0,red,M
...,...,...,...,...,...,...,...
235,38940,374830.000000,1356.0000,-9.93,5,blue,O
236,30839,834042.000000,1194.0000,-10.63,5,blue,O
237,8829,537493.000000,1423.0000,-10.73,5,white,A
238,9235,404940.000000,1112.0000,-11.23,5,white,A
239,37882,294903.000000,1783.0000,-7.80,5,blue,O

In [ ]:
# encoding the Star color

In [38]:
from sklearn.preprocessing import LabelEncoder

In [26]:
l = LabelEncoder()

In [28]:
df['Star color'] = l.fit_transform(df['Star color'])

In [30]:
df['Spectral Class'] = l.fit_transform(df['Spectral Class'])

In [33]:
df

,Temperature (K),Luminosity(L/Lo),Radius(R/Ro),Absolute magnitude(Mv),Star type,Star color,Spectral Class
0,3068,0.002400,0.1700,16.12,0,5,5
1,3042,0.000500,0.1542,16.60,0,5,5
2,2600,0.000300,0.1020,18.70,0,5,5
3,2800,0.000200,0.1600,16.65,0,5,5
4,1939,0.000138,0.1030,20.06,0,5,5
...,...,...,...,...,...,...,...
235,38940,374830.000000,1356.0000,-9.93,5,0,6
236,30839,834042.000000,1194.0000,-10.63,5,0,6
237,8829,537493.000000,1423.0000,-10.73,5,6,0
238,9235,404940.000000,1112.0000,-11.23,5,6,0
239,37882,294903.000000,1783.0000,-7.80,5,0,6

In [34]:
df['Star color'].nunique()

11